### ISSUE TITLE
Babel dependency error on startup in 1.0.0

### ISSUE THREAD

**Issue by lizadaly** [lizadaly/windrift-starter#9]
Running with the latest windrift (1.0.2), a downstream configuration is complaining about a missing plugin.

```
    ERROR in ./~/redux-undo/lib/index.js
    Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/lizadaly/github/windrift-starter/node_modules/redux-undo/.babelrc" at 0, attempted to resolve relative to "/Users/lizadaly/github/windrift-starter/node_modules/redux-undo"
        at /Users/lizadaly/github/windrift-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
        at Array.map (native)
        at Function.normalisePlugins (/Users/lizadaly/github/windrift-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
        at OptionManager.mergeOptions (/Users/lizadaly/github/windrift-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
        at OptionManager.init (/Users/lizadaly/github/windrift-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
        at File.initOptions (/Users/lizadaly/github/windrift-starter/node_modules/babel-core/lib/transformation/file/index.js:212:65)
        at new File (/Users/lizadaly/github/windrift-starter/node_modules/babel-core/lib/transformation/file/index.js:135:24)
        at Pipeline.transform (/Users/lizadaly/github/windrift-starter/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
        at transpile (/Users/lizadaly/github/windrift-starter/node_modules/babel-loader/lib/index.js:49:20)
        at /Users/lizadaly/github/windrift-starter/node_modules/babel-loader/lib/fs-cache.js:118:18
        at ReadFileContext.callback (/Users/lizadaly/github/windrift-starter/node_modules/babel-loader/lib/fs-cache.js:31:21)
        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:358:13)
     @ ./~/windrift/src/app.js 18:17-38
     @ ./~/windrift/src/index.js
     @ ./index.js
     @ multi (webpack)-dev-server/client?http://localhost:8081 ./index.js webpack-dev-server/client?http://localhost:8080
```

**Comment by lizadaly** [comment]
Resolved by adding the plugin dependency (but don't enable it in local .babelrc; the chapter loader depends on the Babel 6 behavior).
